# Generated by Django 6.0.1 on 2026-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saas_plan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
