# Generated by Django 4.2.7 on 2026-01-21 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0004_transaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('webhook_secret', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(default=list)),
                ('allowed_ips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=1)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='merchants.webhookconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('refund_id', models.CharField(max_length=200, unique=True)),
                ('gateway_response', models.JSONField(default=dict)),
                ('processor', models.CharField(default='routebase', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_method', models.CharField(choices=[('ORIGINAL', 'Original Payment Method'), ('BANK_TRANSFER', 'Bank Transfer'), ('JAZZCASH', 'JazzCash'), ('EASYPAYSA', 'EasyPaisa'), ('RAAST', 'Raast')], default='ORIGINAL', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='merchants.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payout_id', models.CharField(max_length=200, unique=True)),
                ('gateway_response', models.JSONField(default=dict)),
                ('bank_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('JAZZCASH', 'JazzCash'), ('EASYPAYSA', 'EasyPaisa'), ('RAAST', 'Raast')], max_length=20)),
                ('bank_account', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('bank_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
